"""Add social platform connections and posts models

Revision ID: 008_add_social_platform_connections
Revises: 007_add_external_post_id_to_contentlog
Create Date: 2025-01-18 12:00:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '008a_add_social_platform_connections'
down_revision = '008'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Create social_platform_connections table
    op.create_table('social_platform_connections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('platform', sa.String(), nullable=False),
    sa.Column('platform_user_id', sa.String(), nullable=False),
    sa.Column('platform_username', sa.String(), nullable=False),
    sa.Column('platform_display_name', sa.String(), nullable=True),
    sa.Column('profile_image_url', sa.String(), nullable=True),
    sa.Column('profile_url', sa.String(), nullable=True),
    sa.Column('access_token', sa.Text(), nullable=False),
    sa.Column('refresh_token', sa.Text(), nullable=True),
    sa.Column('token_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('token_type', sa.String(), nullable=True),
    sa.Column('scope', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('connection_status', sa.String(), nullable=True),
    sa.Column('platform_metadata', sa.JSON(), nullable=True),
    sa.Column('rate_limit_remaining', sa.Integer(), nullable=True),
    sa.Column('rate_limit_reset', sa.DateTime(timezone=True), nullable=True),
    sa.Column('daily_post_count', sa.Integer(), nullable=True),
    sa.Column('daily_post_limit', sa.Integer(), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('error_count', sa.Integer(), nullable=True),
    sa.Column('last_error_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('auto_post_enabled', sa.Boolean(), nullable=True),
    sa.Column('preferred_posting_times', sa.JSON(), nullable=True),
    sa.Column('content_filters', sa.JSON(), nullable=True),
    sa.Column('connected_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_refreshed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_social_conn_platform_user', 'social_platform_connections', ['platform', 'platform_user_id'], unique=False)
    op.create_index('idx_social_conn_user_platform', 'social_platform_connections', ['user_id', 'platform'], unique=False)
    op.create_index(op.f('ix_social_platform_connections_id'), 'social_platform_connections', ['id'], unique=False)
    op.create_index(op.f('ix_social_platform_connections_is_active'), 'social_platform_connections', ['is_active'], unique=False)
    op.create_index(op.f('ix_social_platform_connections_platform'), 'social_platform_connections', ['platform'], unique=False)
    op.create_index(op.f('ix_social_platform_connections_platform_user_id'), 'social_platform_connections', ['platform_user_id'], unique=False)
    op.create_index(op.f('ix_social_platform_connections_user_id'), 'social_platform_connections', ['user_id'], unique=False)

    # Create social_posts table
    op.create_table('social_posts',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('connection_id', sa.Integer(), nullable=False),
    sa.Column('content_item_id', sa.String(), nullable=True),
    sa.Column('platform', sa.String(), nullable=False),
    sa.Column('platform_post_id', sa.String(), nullable=False),
    sa.Column('platform_url', sa.String(), nullable=True),
    sa.Column('content_text', sa.Text(), nullable=True),
    sa.Column('media_urls', sa.JSON(), nullable=True),
    sa.Column('hashtags', sa.JSON(), nullable=True),
    sa.Column('mentions', sa.JSON(), nullable=True),
    sa.Column('post_type', sa.String(), nullable=True),
    sa.Column('post_format', sa.String(), nullable=True),
    sa.Column('scheduled_for', sa.DateTime(timezone=True), nullable=True),
    sa.Column('posted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('failure_reason', sa.Text(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=True),
    sa.Column('likes_count', sa.Integer(), nullable=True),
    sa.Column('shares_count', sa.Integer(), nullable=True),
    sa.Column('comments_count', sa.Integer(), nullable=True),
    sa.Column('reach_count', sa.Integer(), nullable=True),
    sa.Column('click_count', sa.Integer(), nullable=True),
    sa.Column('engagement_rate', sa.Float(), nullable=True),
    sa.Column('last_metrics_update', sa.DateTime(timezone=True), nullable=True),
    sa.Column('metrics_update_count', sa.Integer(), nullable=True),
    sa.Column('peak_engagement_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('platform_metrics', sa.JSON(), nullable=True),
    sa.Column('sentiment', sa.String(), nullable=True),
    sa.Column('topics', sa.JSON(), nullable=True),
    sa.Column('keywords', sa.JSON(), nullable=True),
    sa.Column('campaign_id', sa.String(), nullable=True),
    sa.Column('utm_parameters', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['connection_id'], ['social_platform_connections.id'], ),
    sa.ForeignKeyConstraint(['content_item_id'], ['content_items.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_social_post_campaign', 'social_posts', ['campaign_id'], unique=False)
    op.create_index('idx_social_post_connection_status', 'social_posts', ['connection_id', 'status'], unique=False)
    op.create_index('idx_social_post_posted_engagement', 'social_posts', ['posted_at', 'engagement_rate'], unique=False)
    op.create_index('idx_social_post_user_platform', 'social_posts', ['user_id', 'platform'], unique=False)
    op.create_index(op.f('ix_social_posts_campaign_id'), 'social_posts', ['campaign_id'], unique=False)
    op.create_index(op.f('ix_social_posts_created_at'), 'social_posts', ['created_at'], unique=False)
    op.create_index(op.f('ix_social_posts_platform'), 'social_posts', ['platform'], unique=False)
    op.create_index(op.f('ix_social_posts_platform_post_id'), 'social_posts', ['platform_post_id'], unique=False)
    op.create_index(op.f('ix_social_posts_posted_at'), 'social_posts', ['posted_at'], unique=False)
    op.create_index(op.f('ix_social_posts_status'), 'social_posts', ['status'], unique=False)
    op.create_index(op.f('ix_social_posts_user_id'), 'social_posts', ['user_id'], unique=False)

    # Create platform_metrics_snapshots table
    op.create_table('platform_metrics_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('connection_id', sa.Integer(), nullable=False),
    sa.Column('snapshot_time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('followers_count', sa.Integer(), nullable=True),
    sa.Column('following_count', sa.Integer(), nullable=True),
    sa.Column('posts_count', sa.Integer(), nullable=True),
    sa.Column('avg_likes_per_post', sa.Float(), nullable=True),
    sa.Column('avg_comments_per_post', sa.Float(), nullable=True),
    sa.Column('avg_shares_per_post', sa.Float(), nullable=True),
    sa.Column('overall_engagement_rate', sa.Float(), nullable=True),
    sa.Column('followers_growth', sa.Integer(), nullable=True),
    sa.Column('posts_growth', sa.Integer(), nullable=True),
    sa.Column('engagement_growth', sa.Float(), nullable=True),
    sa.Column('platform_specific_metrics', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['connection_id'], ['social_platform_connections.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_metrics_snapshot_conn_time', 'platform_metrics_snapshots', ['connection_id', 'snapshot_time'], unique=False)
    op.create_index(op.f('ix_platform_metrics_snapshots_id'), 'platform_metrics_snapshots', ['id'], unique=False)
    op.create_index(op.f('ix_platform_metrics_snapshots_snapshot_time'), 'platform_metrics_snapshots', ['snapshot_time'], unique=False)

    # Create social_post_templates table
    op.create_table('social_post_templates',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('platform', sa.String(), nullable=False),
    sa.Column('post_type', sa.String(), nullable=False),
    sa.Column('template_text', sa.Text(), nullable=False),
    sa.Column('hashtag_template', sa.String(), nullable=True),
    sa.Column('max_length', sa.Integer(), nullable=True),
    sa.Column('thread_split_rules', sa.JSON(), nullable=True),
    sa.Column('formatting_rules', sa.JSON(), nullable=True),
    sa.Column('usage_count', sa.Integer(), nullable=True),
    sa.Column('avg_engagement_rate', sa.Float(), nullable=True),
    sa.Column('variables', sa.JSON(), nullable=True),
    sa.Column('required_media', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_social_template_user_platform', 'social_post_templates', ['user_id', 'platform'], unique=False)
    op.create_index(op.f('ix_social_post_templates_platform'), 'social_post_templates', ['platform'], unique=False)

    # Set default values for new columns
    op.execute("UPDATE social_platform_connections SET is_active = true WHERE is_active IS NULL")
    op.execute("UPDATE social_platform_connections SET is_verified = false WHERE is_verified IS NULL")
    op.execute("UPDATE social_platform_connections SET connection_status = 'connected' WHERE connection_status IS NULL")
    op.execute("UPDATE social_platform_connections SET platform_metadata = '{}' WHERE platform_metadata IS NULL")
    op.execute("UPDATE social_platform_connections SET daily_post_count = 0 WHERE daily_post_count IS NULL")
    op.execute("UPDATE social_platform_connections SET error_count = 0 WHERE error_count IS NULL")
    op.execute("UPDATE social_platform_connections SET auto_post_enabled = true WHERE auto_post_enabled IS NULL")
    op.execute("UPDATE social_platform_connections SET preferred_posting_times = '{}' WHERE preferred_posting_times IS NULL")
    op.execute("UPDATE social_platform_connections SET content_filters = '{}' WHERE content_filters IS NULL")

    op.execute("UPDATE social_posts SET status = 'draft' WHERE status IS NULL")
    op.execute("UPDATE social_posts SET post_type = 'text' WHERE post_type IS NULL")
    op.execute("UPDATE social_posts SET media_urls = '[]' WHERE media_urls IS NULL")
    op.execute("UPDATE social_posts SET hashtags = '[]' WHERE hashtags IS NULL")
    op.execute("UPDATE social_posts SET mentions = '[]' WHERE mentions IS NULL")
    op.execute("UPDATE social_posts SET likes_count = 0 WHERE likes_count IS NULL")
    op.execute("UPDATE social_posts SET shares_count = 0 WHERE shares_count IS NULL")
    op.execute("UPDATE social_posts SET comments_count = 0 WHERE comments_count IS NULL")
    op.execute("UPDATE social_posts SET reach_count = 0 WHERE reach_count IS NULL")
    op.execute("UPDATE social_posts SET click_count = 0 WHERE click_count IS NULL")
    op.execute("UPDATE social_posts SET engagement_rate = 0.0 WHERE engagement_rate IS NULL")
    op.execute("UPDATE social_posts SET retry_count = 0 WHERE retry_count IS NULL")
    op.execute("UPDATE social_posts SET metrics_update_count = 0 WHERE metrics_update_count IS NULL")
    op.execute("UPDATE social_posts SET platform_metrics = '{}' WHERE platform_metrics IS NULL")
    op.execute("UPDATE social_posts SET topics = '[]' WHERE topics IS NULL")
    op.execute("UPDATE social_posts SET keywords = '[]' WHERE keywords IS NULL")
    op.execute("UPDATE social_posts SET utm_parameters = '{}' WHERE utm_parameters IS NULL")

    op.execute("UPDATE platform_metrics_snapshots SET followers_count = 0 WHERE followers_count IS NULL")
    op.execute("UPDATE platform_metrics_snapshots SET following_count = 0 WHERE following_count IS NULL")
    op.execute("UPDATE platform_metrics_snapshots SET posts_count = 0 WHERE posts_count IS NULL")
    op.execute("UPDATE platform_metrics_snapshots SET avg_likes_per_post = 0.0 WHERE avg_likes_per_post IS NULL")
    op.execute("UPDATE platform_metrics_snapshots SET avg_comments_per_post = 0.0 WHERE avg_comments_per_post IS NULL")
    op.execute("UPDATE platform_metrics_snapshots SET avg_shares_per_post = 0.0 WHERE avg_shares_per_post IS NULL")
    op.execute("UPDATE platform_metrics_snapshots SET overall_engagement_rate = 0.0 WHERE overall_engagement_rate IS NULL")
    op.execute("UPDATE platform_metrics_snapshots SET followers_growth = 0 WHERE followers_growth IS NULL")
    op.execute("UPDATE platform_metrics_snapshots SET posts_growth = 0 WHERE posts_growth IS NULL")
    op.execute("UPDATE platform_metrics_snapshots SET engagement_growth = 0.0 WHERE engagement_growth IS NULL")
    op.execute("UPDATE platform_metrics_snapshots SET platform_specific_metrics = '{}' WHERE platform_specific_metrics IS NULL")

    op.execute("UPDATE social_post_templates SET usage_count = 0 WHERE usage_count IS NULL")
    op.execute("UPDATE social_post_templates SET avg_engagement_rate = 0.0 WHERE avg_engagement_rate IS NULL")
    op.execute("UPDATE social_post_templates SET variables = '[]' WHERE variables IS NULL")
    op.execute("UPDATE social_post_templates SET required_media = false WHERE required_media IS NULL")
    op.execute("UPDATE social_post_templates SET is_active = true WHERE is_active IS NULL")
    op.execute("UPDATE social_post_templates SET thread_split_rules = '{}' WHERE thread_split_rules IS NULL")
    op.execute("UPDATE social_post_templates SET formatting_rules = '{}' WHERE formatting_rules IS NULL")

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_social_post_templates_platform'), table_name='social_post_templates')
    op.drop_index('idx_social_template_user_platform', table_name='social_post_templates')
    op.drop_table('social_post_templates')
    op.drop_index(op.f('ix_platform_metrics_snapshots_snapshot_time'), table_name='platform_metrics_snapshots')
    op.drop_index(op.f('ix_platform_metrics_snapshots_id'), table_name='platform_metrics_snapshots')
    op.drop_index('idx_metrics_snapshot_conn_time', table_name='platform_metrics_snapshots')
    op.drop_table('platform_metrics_snapshots')
    op.drop_index(op.f('ix_social_posts_user_id'), table_name='social_posts')
    op.drop_index(op.f('ix_social_posts_status'), table_name='social_posts')
    op.drop_index(op.f('ix_social_posts_posted_at'), table_name='social_posts')
    op.drop_index(op.f('ix_social_posts_platform_post_id'), table_name='social_posts')
    op.drop_index(op.f('ix_social_posts_platform'), table_name='social_posts')
    op.drop_index(op.f('ix_social_posts_created_at'), table_name='social_posts')
    op.drop_index(op.f('ix_social_posts_campaign_id'), table_name='social_posts')
    op.drop_index('idx_social_post_user_platform', table_name='social_posts')
    op.drop_index('idx_social_post_posted_engagement', table_name='social_posts')
    op.drop_index('idx_social_post_connection_status', table_name='social_posts')
    op.drop_index('idx_social_post_campaign', table_name='social_posts')
    op.drop_table('social_posts')
    op.drop_index(op.f('ix_social_platform_connections_user_id'), table_name='social_platform_connections')
    op.drop_index(op.f('ix_social_platform_connections_platform_user_id'), table_name='social_platform_connections')
    op.drop_index(op.f('ix_social_platform_connections_platform'), table_name='social_platform_connections')
    op.drop_index(op.f('ix_social_platform_connections_is_active'), table_name='social_platform_connections')
    op.drop_index(op.f('ix_social_platform_connections_id'), table_name='social_platform_connections')
    op.drop_index('idx_social_conn_user_platform', table_name='social_platform_connections')
    op.drop_index('idx_social_conn_platform_user', table_name='social_platform_connections')
    op.drop_table('social_platform_connections')
    # ### end Alembic commands ###